web:
    enabled: true
    tonerlevel: { warning: 30, danger: 10 }
slack:
    enabled: true
    tonerlevel: { warning: 30, danger: 10 }
email:
    enabled: true
    tonerlevel: { warning: 30, danger: 10 }
monitoring:
    enabled: true
    tonerlevel: { warning: 0, danger: 5 }
